### ISSUE TITLE
many failed hunks

### ISSUE THREAD

**Issue by jaccc** [dapperlinux/dapper-secure-kernel-patchset-stable#10]
There are many failed hunks with 4.9.119. Is it expected? It was similar with 4.9.114.
[dry-4.9.119.txt.gz](https://github.com/dapperlinux/dapper-secure-kernel-patchset-stable/files/2290124/dry-4.9.119.txt.gz)

**Comment by miroR** [comment]
Hi @jacc Nope! It must be something other the reasons for your hunks. I re-checked it, and it patches perfectly clean. No hunks, no failed patched files.

**Comment by jaccc** [comment]
upstream patch is applied successfully
patch -p1  < patch-4.9.119
attached file is output from
patch -p1 --dry-run < dapper-secure-kernel-patchset-4.9.119-2018-08-10.patch

**Comment by jaccc** [comment]
does also --dry-run work without failed hunks?

**Comment by msr50** [comment]
Hi jaccc. Everything patches cleanly - I have NEVER released a patchset which fails to patch cleanly. Sure, from time to time I accidentally leave in a meltdown or spectre mitigation thats broken, but I never ship the patchset with failing hunks.

It patches cleanly with both the patch command and git -am. 

If you ever want to verify this for yourself, clone the repo, and run the following:
```
./create_test.sh # This concatenates all the small patches into one large one
./test_patch.sh # This tests the generated patchset for merge problems and failed hunks
# and if the patchset patches cleanly
./make_release.sh # This generates and outputs a patchset fit for release that works with both patch and git
```
I tend to use a lot of temporary extractions of the kernel, and if the patch fails, I tend to delete it and get a fresh copy, so I don't use --dry-run myself.

Something to be aware of is that the patchset is really two patchsets, and it has been this way since 4.9.75 and onward. This is because I need to revert all the upstream meltdown and spectre mitigations and then patch the dappersec patchset, since dappersec is not compatible with those mitigations. I know I could have shipped it as one patchset, but I decided that if anyone wanted to ever audit the patchset or take over from me for any reason, that it is easier to understand that one patchset reverts meltdown and spectre fixes, and the other patches on dappersec features.

Maybe dry run doesn't like the fact that the patchset is really two patchsets? I have heard some noises from gentoo users whose build systems don't like two patchsets being combined into the one. I'm not going to change it though, since patch and git -am still work just fine. 

Anyway, just use patch normally, and don't dry run. If something is broken (unlikely), you can always delete the directory and unextract again.

PS: 4.9.120 looks like a scary patch, I'll keep doing my best to keep things running. New patchset will be out either today or in the next few days.

**Comment by jacc** [comment]
you tagged the wrong jacc

**Comment by jaccc** [comment]
is there following error with dapper-secure-kernel-patchset-4.9.131-2018-10-07.patch
without dry-run?

patching file arch/x86/include/asm/asm-prototypes.h
Hunk #1 FAILED at 10.
1 out of 1 hunk FAILED -- saving rejects to file arch/x86/include/asm/asm-prototypes.h.rej
