### ISSUE TITLE
nospec.h missing in 4.9.115 patch

### ISSUE THREAD

**Issue by karesmakro** [dapperlinux/dapper-secure-kernel-patchset-stable#9]
At first, great thanks for your great work!
The latest patch has a problem with nospec.h missing. 
```
drivers/vfio/pci/vfio_pci.c:31:26: fatal error: linux/nospec.h: Datei oder Verzeichnis nicht gefunden
 #include <linux/nospec.h>
```

**Comment by miroR** [comment]
Confirmed here. Ijust tried compiling it and got that error. Apparently some retpoline code, not present in grsec-dappersec, will probably be a relatively quick fix for @msr50

**Comment by msr50** [comment]
Sorry about that little hiccup. I was in a bit of a hurry today, and I probably should have re-read each commit twice, and it seems one incompatible one slipped through. I did notice my own build fail this afternoon, but I was low on time and could not debug it. Thanks for reporting, its useful.

Fixed in https://github.com/dapperlinux/dapper-secure-kernel-patchset-stable/commit/55bd576474aebbfabe5bcf278648af558fa5ad9d

You can download version 4.9.115a and it should work.
